name: asep_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_local_notifications: ^17.0.0
  phone_state: ^2.1.1
  flutter:
    sdk: flutter
  http: ^1.3.0
  mongo_dart: ^0.10.5
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.14
  sqflite: ^2.4.2
  intl: ^0.20.2
  path: ^1.8.2
  sqflite_common_ffi: ^2.3.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.2.5  
  permission_handler: ^11.3.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2  
  flutter_dotenv: ^5.2.1
  flutter_contacts: ^1.1.9


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/.env

  fonts:
   - family: Poppins
     fonts:
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
